"""Issues list + detail. Phase 3 verification handoff endpoint also lives
here so the dashboard can fetch the Claude Code prompt bundle (Phase 4)."""

from __future__ import annotations

from typing import Any
from uuid import UUID

from fastapi import APIRouter, HTTPException, Query, status

from ..auth import CurrentUser
from ..db import get_pool
from ..models import Issue

router = APIRouter()


@router.get("", response_model=list[Issue])
async def list_issues(
    ctx: CurrentUser,
    status_filter: str | None = Query(default=None, alias="status"),
    limit: int = Query(default=100, le=500),
) -> list[Issue]:
    pool = await get_pool()
    async with pool.acquire() as conn:
        if status_filter:
            rows = await conn.fetch(
                """
                SELECT * FROM issues
                 WHERE tenant_id = $1 AND status = $2
                 ORDER BY opened_at DESC
                 LIMIT $3
                """,
                UUID(ctx.tenant_id),
                status_filter,
                limit,
            )
        else:
            rows = await conn.fetch(
                """
                SELECT * FROM issues
                 WHERE tenant_id = $1
                 ORDER BY opened_at DESC
                 LIMIT $2
                """,
                UUID(ctx.tenant_id),
                limit,
            )
    return [Issue.model_validate(dict(r)) for r in rows]


@router.get("/{issue_id}", response_model=Issue)
async def get_issue(issue_id: UUID, ctx: CurrentUser) -> Issue:
    pool = await get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT * FROM issues WHERE id = $1 AND tenant_id = $2",
            issue_id,
            UUID(ctx.tenant_id),
        )
    if row is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND)
    return Issue.model_validate(dict(row))


@router.get("/{issue_id}/handoff")
async def claude_code_handoff(issue_id: UUID, ctx: CurrentUser) -> dict[str, Any]:
    """Phase 4: produce a Claude Code-ready prompt bundling root cause +
    affected files + verification plan. The dashboard's "Copy as Claude Code
    prompt" button fetches this and copies the `prompt` field."""
    pool = await get_pool()
    async with pool.acquire() as conn:
        issue = await conn.fetchrow(
            "SELECT * FROM issues WHERE id = $1 AND tenant_id = $2",
            issue_id,
            UUID(ctx.tenant_id),
        )
        if issue is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND)
        finding = await conn.fetchrow(
            """
            SELECT f.* FROM findings f
              JOIN sessions s ON s.id = f.session_id
             WHERE s.id = $1
             ORDER BY f.created_at DESC
             LIMIT 1
            """,
            issue["opened_by_session_id"],
        )
        agent = await conn.fetchrow(
            "SELECT * FROM agents WHERE id = $1",
            issue["agent_id"],
        )

    if finding is None or agent is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="evidence missing")

    prompt = _render_handoff_prompt(
        issue=dict(issue), finding=dict(finding), agent=dict(agent)
    )
    return {
        "issue_id": str(issue_id),
        "prompt": prompt,
        "evidence": dict(finding)["evidence"],
        "repo": agent["github_repo"],
    }


def _render_handoff_prompt(*, issue: dict, finding: dict, agent: dict) -> str:
    import json
    evidence = finding["evidence"]
    if isinstance(evidence, str):
        evidence = json.loads(evidence)
    affected = evidence.get("affected_files", [])
    affected_md = "\n".join(f"- `{f}`" for f in affected) or "(unknown)"
    return f"""# Fix request from TigerLite

## Root cause
{finding["summary"]}

## Affected files
{affected_md}

## Suggested action
{finding.get("suggested_action") or "(none recorded)"}

## Verification
After your fix, watch the agent at `{agent["name"]}` and confirm metrics
return to baseline. Recovery criteria:
{json.dumps(evidence.get("recovery_criteria", {}), indent=2)}

## Repo
{agent.get("github_repo") or "(no repo connected)"}

## Issue ID
{issue["id"]}

---
This prompt was generated by TigerLite. The agent's full reasoning chain
lives in session {issue["opened_by_session_id"]} for audit.
"""
